//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class posts {
    
    private postsRow[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("row", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public postsRow[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class postsRow {
    
    private string idField;
    
    private string postTypeIdField;
    
    private string acceptedAnswerIdField;
    
    private string creationDateField;
    
    private string scoreField;
    
    private string viewCountField;
    
    private string bodyField;
    
    private string ownerUserIdField;
    
    private string lastEditorUserIdField;
    
    private string lastEditDateField;
    
    private string lastActivityDateField;
    
    private string titleField;
    
    private string tagsField;
    
    private string answerCountField;
    
    private string favoriteCountField;
    
    private string commentCountField;
    
    private string parentIdField;
    
    private string communityOwnedDateField;
    
    private string lastEditorDisplayNameField;
    
    private string closedDateField;
    
    private string ownerDisplayNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PostTypeId {
        get {
            return this.postTypeIdField;
        }
        set {
            this.postTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AcceptedAnswerId {
        get {
            return this.acceptedAnswerIdField;
        }
        set {
            this.acceptedAnswerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ViewCount {
        get {
            return this.viewCountField;
        }
        set {
            this.viewCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OwnerUserId {
        get {
            return this.ownerUserIdField;
        }
        set {
            this.ownerUserIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LastEditorUserId {
        get {
            return this.lastEditorUserIdField;
        }
        set {
            this.lastEditorUserIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LastEditDate {
        get {
            return this.lastEditDateField;
        }
        set {
            this.lastEditDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LastActivityDate {
        get {
            return this.lastActivityDateField;
        }
        set {
            this.lastActivityDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AnswerCount {
        get {
            return this.answerCountField;
        }
        set {
            this.answerCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FavoriteCount {
        get {
            return this.favoriteCountField;
        }
        set {
            this.favoriteCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CommentCount {
        get {
            return this.commentCountField;
        }
        set {
            this.commentCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParentId {
        get {
            return this.parentIdField;
        }
        set {
            this.parentIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CommunityOwnedDate {
        get {
            return this.communityOwnedDateField;
        }
        set {
            this.communityOwnedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LastEditorDisplayName {
        get {
            return this.lastEditorDisplayNameField;
        }
        set {
            this.lastEditorDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClosedDate {
        get {
            return this.closedDateField;
        }
        set {
            this.closedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OwnerDisplayName {
        get {
            return this.ownerDisplayNameField;
        }
        set {
            this.ownerDisplayNameField = value;
        }
    }
}
